[book]
authors = ["HugoPhi"]
language = "en"
multilingual = false
src = "src"
title = "Data Structures in Rust by Hand"

[output.html]
default-theme = "dark"
preferred-dark-theme = "Ayu"

[preprocessor.katex]
