[book]
authors = ["HugoPhi"]
language = "en"
multilingual = false
src = "src"
title = "Data Structures in Rust by Hand"

[output.html]
theme = "theme"
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/HugoPhi/stl.rust"
git-repository-icon = "fa-github"

[preprocessor.katex]
